//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from RecipeLanguage.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="RecipeLanguageParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IRecipeLanguageListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecipeLanguageParser.recipe"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRecipe([NotNull] RecipeLanguageParser.RecipeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecipeLanguageParser.recipe"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRecipe([NotNull] RecipeLanguageParser.RecipeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecipeLanguageParser.statement_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement_list([NotNull] RecipeLanguageParser.Statement_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecipeLanguageParser.statement_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement_list([NotNull] RecipeLanguageParser.Statement_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecipeLanguageParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] RecipeLanguageParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecipeLanguageParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] RecipeLanguageParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecipeLanguageParser.method"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethod([NotNull] RecipeLanguageParser.MethodContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecipeLanguageParser.method"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethod([NotNull] RecipeLanguageParser.MethodContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecipeLanguageParser.ingredient"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIngredient([NotNull] RecipeLanguageParser.IngredientContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecipeLanguageParser.ingredient"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIngredient([NotNull] RecipeLanguageParser.IngredientContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecipeLanguageParser.ask"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAsk([NotNull] RecipeLanguageParser.AskContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecipeLanguageParser.ask"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAsk([NotNull] RecipeLanguageParser.AskContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecipeLanguageParser.speak"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSpeak([NotNull] RecipeLanguageParser.SpeakContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecipeLanguageParser.speak"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSpeak([NotNull] RecipeLanguageParser.SpeakContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecipeLanguageParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment([NotNull] RecipeLanguageParser.AssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecipeLanguageParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment([NotNull] RecipeLanguageParser.AssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecipeLanguageParser.if_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIf_statement([NotNull] RecipeLanguageParser.If_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecipeLanguageParser.if_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIf_statement([NotNull] RecipeLanguageParser.If_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecipeLanguageParser.loop_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLoop_statement([NotNull] RecipeLanguageParser.Loop_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecipeLanguageParser.loop_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLoop_statement([NotNull] RecipeLanguageParser.Loop_statementContext context);
}
