//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from RecipeLanguage.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IRecipeLanguageListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class RecipeLanguageBaseListener : IRecipeLanguageListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecipeLanguageParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] RecipeLanguageParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecipeLanguageParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] RecipeLanguageParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecipeLanguageParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] RecipeLanguageParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecipeLanguageParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] RecipeLanguageParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecipeLanguageParser.askStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAskStatement([NotNull] RecipeLanguageParser.AskStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecipeLanguageParser.askStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAskStatement([NotNull] RecipeLanguageParser.AskStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecipeLanguageParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclaration([NotNull] RecipeLanguageParser.DeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecipeLanguageParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclaration([NotNull] RecipeLanguageParser.DeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecipeLanguageParser.ingredientDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIngredientDeclaration([NotNull] RecipeLanguageParser.IngredientDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecipeLanguageParser.ingredientDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIngredientDeclaration([NotNull] RecipeLanguageParser.IngredientDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecipeLanguageParser.arrayDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayDeclaration([NotNull] RecipeLanguageParser.ArrayDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecipeLanguageParser.arrayDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayDeclaration([NotNull] RecipeLanguageParser.ArrayDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecipeLanguageParser.speakStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpeakStatement([NotNull] RecipeLanguageParser.SpeakStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecipeLanguageParser.speakStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpeakStatement([NotNull] RecipeLanguageParser.SpeakStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecipeLanguageParser.shareStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterShareStatement([NotNull] RecipeLanguageParser.ShareStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecipeLanguageParser.shareStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitShareStatement([NotNull] RecipeLanguageParser.ShareStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecipeLanguageParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment([NotNull] RecipeLanguageParser.AssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecipeLanguageParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment([NotNull] RecipeLanguageParser.AssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecipeLanguageParser.recipeStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRecipeStatement([NotNull] RecipeLanguageParser.RecipeStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecipeLanguageParser.recipeStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRecipeStatement([NotNull] RecipeLanguageParser.RecipeStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecipeLanguageParser.methodStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodStatement([NotNull] RecipeLanguageParser.MethodStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecipeLanguageParser.methodStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodStatement([NotNull] RecipeLanguageParser.MethodStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecipeLanguageParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionCall([NotNull] RecipeLanguageParser.FunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecipeLanguageParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionCall([NotNull] RecipeLanguageParser.FunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecipeLanguageParser.loopStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoopStatement([NotNull] RecipeLanguageParser.LoopStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecipeLanguageParser.loopStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoopStatement([NotNull] RecipeLanguageParser.LoopStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecipeLanguageParser.conditionalStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConditionalStatement([NotNull] RecipeLanguageParser.ConditionalStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecipeLanguageParser.conditionalStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConditionalStatement([NotNull] RecipeLanguageParser.ConditionalStatementContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
